blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://wordpress.org/support/plugin/usgs-stream-flow-data/
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/ChrisMKindred/KWC-USGS/security/policy
    about: Learn how to notify us for sensitive bugs
  - name: Request a feature
    url: https://github.com/chrismkindred/KWC-USGS/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Create an issue
    url: https://github.com/ChrisMKindred/KWC-USGS/issues/new
    about: Report a reproducable bug
