name: Generate .pot

on: [push]

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress POT Generator
      uses: varunsridharan/action-wp-pot-generator@2.0
      with:
        save_path: './languages'
        item_slug: 'kwc_usgs'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
